### ISSUE TITLE
OPENSSL 1.1 compilation patch adoption

### ISSUE THREAD

**Issue by v20z** [nkhorman/panda-imap#1]
Those days I've noticed your activity on your fork. Please review and adopt patch from Debian project (can be extracted from here: http://http.debian.net/debian/pool/main/u/uw-imap/uw-imap_2007f~dfsg-5.debian.tar.xz) which allowed me to compile and build uw-imap/panda-imap with OPENSSL 1.1

Thank You.

[debian-imap-openssl-patch.txt](https://github.com/nkhorman/panda-imap/files/922191/debian-imap-openssl-patch.txt)

**Comment by nkhorman** [comment]
I've looked at the patch.
Please provide more information about this patch. (Sorry, I don't speak linux)
What problem does it solve ?
Is this strictly an API change issue (openssl 1.0 to openssl 1.1), or is it adding functionality ?
Thanks

**Comment by v20z** [comment]
Hello Neal. Thanks for your attention.

It is not related to Linux. OpenSSL 1.1 makes changes in API/typedefs. So panda-map does not compile due to some structures fields are now directly inaccessible and the compilation process breaks with error in bundled host/cert name verification function ssl_validate_cert():
```
 error: incomplete definition of type 'struct x509_st'
    if (scq) return (*scq) (err,host,cert ? cert->name : "???") ? NIL : "";
```
But also actual version of OpenSSL has its own builtin similar check implementation.

So as I can see, this patch of gentlemen from Debian simply conditionally replaces bundled verification function for supplied feautures of OpenSSL 1.1

This allows to build and run with  new version of OpenSSL 1.1

I have not seen any problems during about half of year of use. This patch originated from Debian. Hope it extends the life of panda-imap project which I sometimes use. Original repository https://github.com/jonabbey/panda-imap looks completely inactive unlike your.

Thank You.

**Comment by nkhorman** [comment]
@v20z Thanks for the additional information, I'll apply the patch.

As for @jonabbey and the root of this fork, he is, I'm told, also deceased.
So I'm just trying to help since my very minor activity of applying the SSL options patch has received some interest on the http://mailman13.u.washington.edu/mailman/listinfo/imap-uw list .

Regards
