### ISSUE TITLE
Need shared library support

### ISSUE THREAD

**Issue by pprindeville** [nkhorman/panda-imap#4]
There's a Fedora packaging [patch](http://pkgs.fedoraproject.org/cgit/rpms/uw-imap.git/tree/imap-2007e-shared.patch) to do exactly that.

Actually, the Fedora tree has several useful improvements or fixes.

Y-a-t'il une possibilité d'integrer cette manip (patch)?

**Comment by pprindeville** [comment]
I should also ask, though it's a separate issue, what's the chance of having a numbered release for use downstream?

**Comment by nkhorman** [comment]
@pprindeville please create a separate issue for numbered releases, as well as for any other specific requests.
Thanks.
